### ISSUE TITLE
Implement new skip mechanism

### ISSUE THREAD

**Issue by acaldas** [powerhouse-inc/document-model#23]
According to the [Document Synchronization Protocol](https://www.notion.so/makerdao-ses/Document-Synchronization-Protocol-ebe52f9b855449deb52ff2144c2d241a?pvs=4#e1b76d6cfff544c8ac2d9dddbeb22cfb), the revision number should be increment only.

Currently, when we want to undo operations we send an UNDO operation which is [not added to the operation history ](https://github.com/powerhouse-inc/document-model/blob/f5e33942fc115c15affb42a4770c62ef35b65f01/src/document/reducer.ts#L62) but [decrements the revision number](https://github.com/powerhouse-inc/document-model/blob/f5e33942fc115c15affb42a4770c62ef35b65f01/src/document/reducer.ts#L31) instead.
Here is the current business logic for the UNDO operation: https://github.com/powerhouse-inc/document-model/blob/f5e33942fc115c15affb42a4770c62ef35b65f01/src/document/actions/index.ts#L11-L41

According to the new specification, the UNDO operation should be added to the operation history with the `skip` param defined.
On top of that, any operation might have a `skip` param.
To redo an operation or a group of operations, they should be resubmitted with an higher revision index.

TODO:
- [ ] Update unit tests for the new mechanism
- [ ] Add `skip` parameter to actions/operationsn
- [ ] <s>Undo previous operations when an operation with `skip` defined is dispatched</s>
- [ ] <s>Always increment revision number</s>
- [ ] <s>Add UNDO operation to operations history</s>
- [ ] <s>Update Redo operation to resubmit undone operations</s>

**Comment by wkampmann** [comment]
I would suggest to 

1. focus on implementing the skip mechanism as a first step (maybe limit this ticket to just that), 
1. implement the garbage collection function which removes skipped operations
1. then make a parallel UNDO/REDO implementation as a feature using this skip mechanism, 
1. and finally remove the current UNDO/REDO logic.

The skip mechanism is not just a way to implement UNDO/REDO in an append-only environment, it will also be used for pruning document history, and be the cornerstone of merging branches later, which will basically be: (1) create a new operation history list with the merged and reshuffled operations from the diverging branches, (2) append the new list of merged/shuffled operations to the history of the target branch with a skip value that skips all the original operations 

![20240111-skip-mechanism-for-merging](https://github.com/powerhouse-inc/document-model/assets/1241878/d15d1c06-a299-465e-9ede-bc62b488274f)

But the skip mechanism does require an update to the core commit logic for operations.
