### ISSUE TITLE
Refactor the document model and the document drive

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/document-model#51]
**5 Main Tasks for this round of Refactoring.** 

- [x] Migration of Helper Functions: Several helper functions created for document operations, such as garbage collection and conflict resolution (7 or 8 functions), have been migrated to the document model. This migration is already completed
- [x] Append-Only Mechanism Implementation: the implementation of the append-only mechanism that accommodates garbage collection of document operations. However, there are still broken tests that need updates, and some code refactoring is necessary to improve readability and functionality.
- [ ] Undo and Redo Mechanism:  This task is marked as the third priority and can be addressed later, but it is something we want to tackl as soon as feasible.
- [x] Removal of 'Updating Operations': As the document model evolves to an append-only system, the need to remove updating operations from documents is required. This task is about simplifying the code by eliminating unnecessary operations, as they are no longer required in an append-only model.
- [ ] Update of Prune Operations: The prune operations within the document model need updates to be compatible with the append-only and skip operations model. We'll update the prune operations with the append only changes.

In general the most work will be in creating test to ensure all parts of the system are working as they should be. 

_Archive_

**List op topics provided by Memo initially**
- Error property into operations (to store errors when the reducer fails)
- Allow append only undo (this can generate an operation with the same index but a bigger skip value)
- Storage layer should communicate to process a next operation
- Document model should be able to work with cleaned operations (garbage collected?)
- Document model should support events and commands (actions and operations)
- Migrate helpers to document model
- Migrate tests to document model
- Migrate _processOperations from document drive to document model, allow communication between document drive storage layer through a callback or a middleware.

**Comment by CallmeT-ty** [comment]
@gpuente Could you help me clean up this issue or check box the items you feel have been completed?

**Comment by gpuente** [comment]
Hello @CallmeT-ty !
I've just updated the check boxes, but basically what's pending is to enable UNDO/REDO + tests and update PRUNE operations + tests

**Comment by gpuente** [comment]
Linked issues:

- [ ] https://github.com/powerhouse-inc/document-model/issues/75
- [ ] https://github.com/powerhouse-inc/document-model/issues/76
- [ ] https://github.com/powerhouse-inc/document-model/issues/77
